In [1]:
import pandas as pd
import numpy as np

## Задание на повторение материала

#### 1
#### Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [2]:
a = np.array([i for i in range (12, 24)])
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

#### 2
#### Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [11]:
a1 = a.reshape(2,6)
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [14]:
a2 = a.reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [15]:
a3 = a.reshape(4,3)
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [17]:
a4 = a.reshape(6, 2)
a4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [21]:
a5 = a.reshape(12, 1)
a5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

#### 3
#### Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [23]:
a6 = a.reshape(2, -1)
a6

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [25]:
a7 = a.reshape(3, -1)
a7

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [26]:
a8 = a.reshape(4, -1)
a8

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [31]:
a9 = a.reshape(-1, 2)
a9

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [33]:
a10 = a.reshape(-1, 1)
a10

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

#### 4
#### Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

#### Да, можно

#### 5
#### Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [62]:
rand = np.random.randn(3, 4)
rand

array([[-2.22205225,  0.80208795, -1.20970063, -1.134643  ],
       [-1.4616875 , -0.5125784 ,  0.28374509, -0.81663159],
       [-1.25993961,  0.14438798, -0.3135464 , -0.51340591]])

In [63]:
rand1 = rand.flatten()
rand1

array([-2.22205225,  0.80208795, -1.20970063, -1.134643  , -1.4616875 ,
       -0.5125784 ,  0.28374509, -0.81663159, -1.25993961,  0.14438798,
       -0.3135464 , -0.51340591])

In [65]:
rand.size == rand1.size

True

#### 6
#### Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [70]:
a = np.arange(20, 0, -1)
a

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1])

#### 7
#### Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [71]:
b = np.arange(20, 1, -2)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

#### Массив а создан с интервалом 1, массив b с интервалом 2, в нем только четные числа и его размер меньше.

#### 8
#### Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [74]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [75]:
b = np.ones((3,2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [76]:
v = np.vstack((a,b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [77]:
v.size

10

#### 9
#### Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [86]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [87]:
A = a.reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [89]:
At = A.transpose()
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [90]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [92]:
B.size

16

In [95]:
np.linalg.det(B)

0.0

#### Так как определитель матрицы равен нулю, то вычислить обратную матрицу невозможно

#### 10
#### Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [106]:
np.random.seed(42)

#### 11
#### Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [112]:
lis = np.arange(16)
lis

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [113]:
c = np.random.choice(lis, 16)
c

array([ 1,  7, 11, 13,  5,  1, 15, 11,  4,  0, 11,  9,  5, 12, 11,  8])

#### 12
#### Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [115]:
c2 = c.reshape(4,4)
c2

array([[ 1,  7, 11, 13],
       [ 5,  1, 15, 11],
       [ 4,  0, 11,  9],
       [ 5, 12, 11,  8]])

In [116]:
c2 = c2 * 10
c2

array([[ 10,  70, 110, 130],
       [ 50,  10, 150, 110],
       [ 40,   0, 110,  90],
       [ 50, 120, 110,  80]])

In [118]:
D = np.add(B, c2)
D

array([[ 15,  84, 133, 162],
       [ 64,  60, 236, 232],
       [ 63,  86, 259, 302],
       [ 82, 242, 322, 382]])

In [119]:
np.linalg.det(D)

-26039199.999999955

In [120]:
np.linalg.matrix_rank(D)

4

In [121]:
D_inv = np.linalg.inv(D)
D_inv

array([[-0.05682356, -0.00670451,  0.01558727,  0.01584688],
       [ 0.00200774,  0.00138176, -0.01099112,  0.00699868],
       [ 0.02426956,  0.03005392, -0.02911149, -0.00553012],
       [-0.00953178, -0.02476958,  0.02815601, -0.00055608]])

#### 13
#### Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [124]:
D_inv[(D_inv < 0)] = 0
D_inv

array([[0.        , 0.        , 0.01558727, 0.01584688],
       [0.00200774, 0.00138176, 0.        , 0.00699868],
       [0.02426956, 0.03005392, 0.        , 0.        ],
       [0.        , 0.        , 0.02815601, 0.        ]])

In [125]:
D_inv[(D_inv > 0)] = 1
D_inv

array([[0., 0., 1., 1.],
       [1., 1., 0., 1.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [138]:
np.where([D_inv == 1], B, c2)

array([[[ 10,  70,  23,  32],
        [ 14,  50, 150, 122],
        [ 23,  86, 110,  90],
        [ 50, 120, 212,  80]]])